services:
  nginx:
    build: requirements/nginx/.
    container_name: nginx
    depends_on:
      - wordpress
      - mariadb
    networks:
      - inception
    ports:
      - "443:443"
    volumes:
      - nginx:/var/www/html
  wordpress:
    env_file: ".env"
    build: requirements/wordpress/.
    container_name: wp-php
    depends_on:
      - mariadb
    networks:
      - inception
    volumes:
      - nginx:/var/www/html
  mariadb:
    build: requirements/mariadb
    container_name: mariadb
    networks:
      - inception
    volumes:
      - db:/var/lib/mysql

networks:
  inception:
    name: inception

volumes:
  db:
    name: db
    driver: local
    driver_opts:
      device: ~/data/db
      o : bind
      type : none
  nginx:
    name: nginx
    driver: local
    driver_opts:
      device: ~/data/wp
      o : bind
      type : none
